"""/api/v1/stylist — multimodal entry point for the DressApp Stylist Agent.

Accepts multipart form-data with either `text` or `voice_audio` (or both).
Returns a JSON envelope containing outfit recommendations, reasoning, and a
base64-encoded MP3 of the spoken reply generated by Deepgram Aura-2.
"""
from __future__ import annotations

import logging
import uuid
from typing import Any

from fastapi import APIRouter, File, Form, HTTPException, UploadFile

from app.services.calendar_service import calendar_service
from app.services.logic import get_styling_advice

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/stylist", tags=["stylist"])


@router.post("")
async def stylist_endpoint(
    text: str | None = Form(default=None),
    voice_audio: UploadFile | None = File(default=None),
    image: UploadFile | None = File(default=None),
    do_infill: bool = Form(default=False),
    infill_prompt: str | None = Form(default=None),
    lat: float | None = Form(default=None),
    lng: float | None = Form(default=None),
    include_calendar: bool = Form(default=False),
    language: str = Form(default="en"),
    voice_id: str = Form(default="aura-2-thalia-en"),
    session_id: str | None = Form(default=None),
    occasion: str | None = Form(default=None),
) -> dict[str, Any]:
    if not text and not voice_audio:
        raise HTTPException(400, "Provide `text` or `voice_audio`.")

    image_bytes: bytes | None = None
    image_mime = "image/jpeg"
    if image is not None:
        image_bytes = await image.read()
        image_mime = image.content_type or "image/jpeg"

    audio_bytes: bytes | None = None
    audio_filename = "audio.webm"
    audio_mime = "audio/webm"
    if voice_audio is not None:
        audio_bytes = await voice_audio.read()
        audio_filename = voice_audio.filename or audio_filename
        audio_mime = voice_audio.content_type or audio_mime

    # Calendar: Phase-1 uses a single mock event when `include_calendar=true`
    # and no OAuth is wired yet. Phase 4 swaps this for the real fetch.
    calendar_events: list[dict[str, Any]] | None = None
    if include_calendar:
        calendar_events = [calendar_service.mock_event(occasion or "Work day")]

    sid = session_id or str(uuid.uuid4())

    try:
        advice = await get_styling_advice(
            session_id=sid,
            image_bytes=image_bytes,
            image_mime=image_mime,
            user_text=text,
            voice_audio=audio_bytes,
            voice_filename=audio_filename,
            voice_mime=audio_mime,
            do_infill=do_infill,
            infill_prompt=infill_prompt,
            lat=lat,
            lng=lng,
            language=language,
            voice_id=voice_id,
            calendar_events=calendar_events,
        )
    except ValueError as exc:
        raise HTTPException(400, str(exc)) from exc
    except RuntimeError as exc:
        logger.exception("Stylist misconfiguration")
        raise HTTPException(503, str(exc)) from exc
    except Exception as exc:  # noqa: BLE001
        logger.exception("Stylist pipeline failed")
        raise HTTPException(500, f"Stylist pipeline error: {exc}") from exc

    return {"session_id": sid, "advice": advice}
